version: "3.8"
services:
  resource-service:
    build: resource-service
    ports:
      - "7002:8080"
    depends_on:
      - resource-service-db
  song-service:
    build: song-service
    ports:
      - "7000:8080"
    depends_on:
      - song-service-db
  resource-service-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=resources
    expose:
      - "5432"
    volumes:
      - resource-service-db:/var/lib/postgresql/data
  song-service-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=songs
    expose:
      - "5432"
    volumes:
      - song-service-db:/var/lib/postgresql/data
volumes:
  resource-service-db:
  song-service-db: