server:
  port: ${SONG_SERVICE_SERVER_PORT}
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    password: ${SONG_SERVICE_DB_PASSWORD}
    username: ${SONG_SERVICE_DB_USERNAME}
    url: ${SONG_SERVICE_DB_URL}
    driver-class-name: org.postgresql.Driver