server:
  port: 7000
spring:
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:7001/songs
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop