server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:5432/songs
    driver-class-name: org.postgresql.Driver