server:
  port: 7002
spring:
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:7003/resources
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
clients:
  song-service: http://localhost:7000