server:
  port: ${RESOURCE_SERVICE_SERVER_PORT}
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    password: ${RESOURCE_SERVICE_DB_PASSWORD}
    username: ${RESOURCE_SERVICE_DB_USERNAME}
    url: ${RESOURCE_SERVICE_DB_URL}
    driver-class-name: org.postgresql.Driver
clients:
  song-service: ${SONG_SERVICE_URL}