server:
  port: ${RESOURCE_SERVICE_SERVER_PORT}
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: ${RESOURCE_SERVICE_DB_PASSWORD}
    username: ${RESOURCE_SERVICE_DB_USERNAME}
    url: ${RESOURCE_SERVICE_DB_URL}
    driver-class-name: org.postgresql.Driver
  application:
    name: resource-service
clients:
  song-service: ${SONG_SERVICE_URL}
  s3:
      url: ${S3_URL}
      bucket: ${S3_BUCKET}
      access_key: ${S3_ACCESS_KEY}
      secret_key: ${S3_SECRET_KEY}