server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://resource-service-db:5432/resources
    driver-class-name: org.postgresql.Driver
clients:
  song-service: http://song-service:8080/songs